float64[] sonar_scan_1 # we assume values between 0 and 1
float64[] sonar_scan_2 # we assume values between 0 and 1
int32 size_image
float64 size_of_pixel
geometry_msgs/Pose initial_guess
float64 potential_for_necessary_peak  # default mostly 0.1 Higher values less peaks, lower values more peaks
---
fsregistration/PotentialSolution2D potential_solution # always calculates the closest peak of the initial guess